# docker-compose.yml
version: "3.8"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - "8080:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:80